Fix/catkin make
sonia-auv/provider_depth pull request #1
Opened 2021-10-10 19:14 UTC by supertoto29

**Warning :** Before creating a pull request, make sure that it does not already exists in the [pull requests](../). Thank you.

## Description
Fix the develop container and completed the read thread.

## How has this been tested ?
Tested locally with the sensor

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2021-10-11 23:17 UTC, Kam0ss requested changes
LGTM, one change to do.

2021-10-11 23:17 UTC, Kam0ss commented on .github/workflows/docker-image-perception-fix.yml
> +          color: danger
This is useless.

2021-10-12 14:53 UTC, Kam0ss commented on .github/workflows/docker-image-perception-fix.yml
> +name: Docker Image CI - Develop Branch
Should be Fix instead of Develop.

2021-10-12 15:53 UTC, supertoto29 commented on .github/workflows/docker-image-perception-fix.yml
> +name: Docker Image CI - Develop Branch
Fix made

2021-10-13 11:35 UTC, 0x72D0 approved these changes
LGTM!

2021-10-14 14:02 UTC, merged